name: leeeeeoy_portfolio
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.0
  flutter: ^3.35.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.2

  hive_flutter: ^1.1.0

  go_router: ^17.0.1

  freezed_annotation: ^3.1.0

  logger: ^2.0.2+1

  # firebase
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  firebase_analytics: ^12.1.0
  firebase_crashlytics: ^5.0.6
  firebase_performance: ^0.11.1+3

  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  get_it: ^9.2.0
  injectable: ^2.3.2
  google_fonts: ^7.0.2
  url_launcher: ^6.2.4
  animated_text_kit: ^4.2.2
  smooth_page_indicator: ^2.0.1
  flutter_svg: ^2.0.10+1
  intl: ^0.20.2

dev_dependencies: 
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  freezed:
  build_runner:
  flutter_gen_runner:
  injectable_generator:
  flutter_native_splash: ^2.4.4


flutter:
  uses-material-design: true

  assets:
    - asset/
    - asset/avokado_app/
    - asset/avokado_web/
    - asset/cafein/
    - asset/celdog/
    - asset/bpp/
    - asset/profile/
    - asset/career/
    - asset/social/
    - asset/skill/


  fonts:
    - family: NotoSansKR
      fonts:
        - asset: font/noto_sans_kr/NotoSansKR-Regular.ttf
          weight: 400
        - asset: font/noto_sans_kr/NotoSansKR-Medium.ttf
          weight: 500
        - asset: font/noto_sans_kr/NotoSansKR-Bold.ttf
          weight: 700

    - family: Pacifico
      fonts:
        - asset: font/pacifico/Pacifico-Regular.ttf
          weight: 400

    - family: ShantellSans
      fonts:
        - asset: font/shantell_sans/ShantellSans-Regular.ttf
          weight: 400
        - asset: font/shantell_sans/ShantellSans-Medium.ttf
          weight: 500
        - asset: font/shantell_sans/ShantellSans-Bold.ttf
          weight: 700

flutter_gen:
  output: lib/asset/
  line_length: 120 

  # Optional
  integrations:
    flutter_svg: true
    lottie: true

flutter_native_splash:
  color: "#42a5f5"
  color_dark: "#000000"
  image: asset/splash.png
  image_dark: asset/splash.png

  android: false
  ios: false
  web: true
  web_image_mode: center